vich_uploader:
    db_driver: orm

    mappings:
        jeu_image:
            uri_prefix: /uploads/jeux
            upload_destination: '%kernel.project_dir%/public/uploads/jeux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
